export default function(hljs) {
	const CFML_KEYWORDS = [
		'if', 'else', 'elseif', 'switch', 'case', 'default', 'for', 'foreach', 'while',
		'do', 'try', 'catch', 'finally', 'return', 'break', 'continue', 'throw',
		'new', 'function', 'var', 'local', 'true', 'false', 'null', 'this',
		'cfabort', 'cfset', 'cfif', 'cfelse', 'cfelseif', 'cfloop', 'cfdump',
		'cfquery', 'cfcache', 'cfparam', 'cfreturn', 'cfscript', 'cfoutput',
		'cfmail', 'cfproperty', 'cfcomponent', 'cfargument', 'cffunction', 'cftry',
		'cfthrow', 'cfcatch', 'cffile', 'cfinclude', 'cfcontent', 'cfmodule', 'cftransaction',
		'cfthread',
	].join('|');

	const CFML_BUILT_INS = [
		'Abs', 'ACos', 'AddSOAPRequestHeader', 'AddSOAPResponseHeader', 'AIGetMetaData',
		'AIHas', 'AjaxOnLoad', 'ApplicationPathCacheClear', 'ApplicationStartTime',
		'ApplicationStop', 'Argon2CheckHash', 'Argon2Hash', 'Argon2Verify', 'Array',
		'ArrayAppend', 'ArrayAvg', 'ArrayClear', 'ArrayContains', 'ArrayContainsNoCase',
		'ArrayDelete', 'ArrayDeleteAt', 'ArrayDeleteNoCase', 'ArrayEach', 'ArrayEvery',
		'ArrayFilter', 'ArrayFind', 'ArrayFindAll', 'ArrayFindAllNoCase', 'ArrayFindNoCase',
		'ArrayFirst', 'ArrayIndexExists', 'ArrayInsertAt', 'ArrayIsDefined', 'ArrayIsEmpty',
		'ArrayLast', 'ArrayLen', 'ArrayMap', 'ArrayMax', 'ArrayMedian', 'ArrayMerge',
		'ArrayMid', 'ArrayMin', 'ArrayNew', 'ArrayPop', 'ArrayPrepend', 'ArrayPush',
		'ArrayReduce', 'ArrayRemoveDuplicates', 'ArrayResize', 'ArrayReverse', 'ArraySet',
		'ArrayShift', 'ArraySlice', 'ArraySome', 'ArraySort', 'ArraySplice', 'ArraySum',
		'ArraySwap', 'ArrayToList', 'ArrayToStruct', 'ArrayUnShift', 'Asc', 'ASin',
		'astFromPath', 'astFromString', 'Atn', 'Base64UrlDecode', 'Base64UrlEncode',
		'BCryptHash', 'BCryptVerify', 'Beat', 'BinaryDecode', 'BinaryEncode', 'BitAnd',
		'BitMaskClear', 'BitMaskRead', 'BitMaskSet', 'BitNot', 'BitOr', 'BitSHLN', 'BitSHRN',
		'BitXor', 'BooleanFormat', 'breakpoint', 'BundleInfo', 'CacheClear', 'CacheCount',
		'CacheDelete', 'CachedWithinFlush', 'CachedWithinId', 'CacheGet', 'CacheGetAll',
		'CacheGetAllIds', 'CacheGetDefaultCacheName', 'CacheGetMetadata', 'CacheGetProperties',
		'CacheIdExists', 'CacheKeyExists', 'CachePut', 'CacheRegionExists', 'CacheRegionNew',
		'CacheRegionRemove', 'CacheRemove', 'CacheRemoveAll', 'CacheSetProperties',
		'CallStackDump', 'CallStackGet', 'Canonicalize', 'CborDecode', 'CborEncode',
		'CborToJson', 'Ceiling', 'CertificateInfo', 'CertificateToPem', 'Cfusion_decrypt',
		'Cfusion_encrypt', 'CharsetDecode', 'CharsetEncode', 'Chr', 'CJustify',
		'ClearTimeZone', 'CollectionEach', 'CollectionEvery', 'CollectionFilter',
		'CollectionMap', 'CollectionReduce', 'CollectionSome', 'Compare', 'CompareNoCase',
		'ComponentCacheClear', 'ComponentCacheList', 'ComponentInfo', 'ComponentListPackage',
		'Compress', 'ConfigImport', 'ConfigMerge', 'configTranslate', 'ContractPath', 'Cos',
		'CoseToKey', 'CreateAISession', 'CreateDate', 'CreateDateTime', 'CreateDynamicProxy',
		'CreateGUID', 'CreateObject', 'CreateODBCDate', 'CreateODBCDateTime', 'CreateODBCTime',
		'CreateTime', 'CreateTimeSpan', 'CreateULID', 'CreateUniqueId', 'CreateUUID',
		'CreateWebSocketClient', 'CSRFGenerateToken', 'CSRFVerifyToken', 'CtCacheClear',
		'CtCacheList', 'DatasourceFlushMetaCache', 'DateAdd', 'DateCompare', 'DateDiff',
		'DateFormat', 'DatePart', 'DateTimeFormat', 'Day', 'DayOfWeek', 'DayOfWeekAsString',
		'DayOfWeekShortAsString', 'DayOfYear', 'DaysInMonth', 'DaysInYear', 'DbPoolClear',
		'DE', 'DebugAdd', 'DecimalFormat', 'DecodeForHtml', 'DecodeFromURL', 'DecrementValue',
		'Decrypt', 'DecryptBinary', 'DeleteClientVariable', 'DeserializeJSON', 'DirectoryCopy',
		'DirectoryCreate', 'DirectoryDelete', 'DirectoryExists', 'DirectoryInfo',
		'DirectoryList', 'DirectoryRename', 'DollarFormat', 'Dump', 'Duplicate', 'Each',
		'EC2describeInstances', 'Echo', 'Empty', 'EncodeForCSS', 'EncodeForDN',
		'EncodeForHTML', 'EncodeForHTMLAttribute', 'EncodeForJavaScript', 'EncodeForLDAP',
		'EncodeForSQL', 'EncodeForURL', 'EncodeForXML', 'EncodeForXMLAttribute',
		'EncodeForXPath', 'Encrypt', 'EncryptBinary', 'EntityDelete', 'EntityLoad',
		'EntityLoadByExample', 'EntityLoadByPK', 'EntityMerge', 'EntityNameArray',
		'EntityNameList', 'EntityNew', 'EntityReload', 'EntitySave', 'EntityToQuery',
		'ESAPIDecode', 'ESAPIEncode', 'Evaluate', 'Exp', 'ExpandPath', 'ExtensionExists',
		'ExtensionInfo', 'ExtensionList', 'Extract', 'FileAppend', 'FileClose', 'FileCopy',
		'FileDelete', 'FileExists', 'FileGetMimeType', 'FileInfo', 'FileIsEOF',
		'FileModeToSymbolic', 'FileMove', 'FileOpen', 'FileRead', 'FileReadBinary',
		'FileReadLine', 'FileSeek', 'FileSetAccessMode', 'FileSetAttribute',
		'FileSetLastModified', 'FileSkipBytes', 'FileTouch', 'FileUpload', 'FileUploadAll',
		'FileWrite', 'FileWriteLine', 'Find', 'FindLast', 'FindLastNoCase', 'FindNoCase',
		'FindOneOf', 'FirstDayOfMonth', 'Fix', 'Floor', 'FormatBaseN', 'GatewayAction',
		'GatewayState', 'Generate3DESKey', 'GenerateArgon2Hash', 'GenerateBCryptHash',
		'GenerateBlake2bHash', 'GenerateBlake2sHash', 'GenerateBlake3Hash', 'GenerateCSR',
		'GenerateHKDFKey', 'GenerateKeyPair', 'GenerateKeystore', 'GeneratePBKDFkey',
		'GenerateRSAkeys', 'GenerateSCryptHash', 'GenerateSecretKey',
		'GenerateSelfSignedCertificate', 'GenerateSignature', 'GetApplicationMetadata',
		'GetApplicationSettings', 'GetAuthUser', 'GetBaseTagData', 'GetBaseTagList',
		'GetBaseTemplatePath', 'GetBuiltInFunction', 'GetCanonicalPath', 'GetClassPath',
		'GetClientVariablesList', 'GetComponentMetaData', 'GetComponentStaticScope',
		'GetContextInfo', 'GetContextRoot', 'GetCPUUsage', 'GetCurrentContext',
		'GetCurrentTemplatePath', 'GetDirectoryFromPath', 'GetEncoding', 'GetFileFromPath',
		'GetFileInfo', 'GetFreeSpace', 'GetFunctionCalledName', 'GetFunctionData',
		'GetFunctionKeywords', 'GetFunctionList', 'GetHTTPRequestData',
		'GetHTTPRequestHeaders', 'GetHttpTimeString', 'GetK2ServerDocCount',
		'GetK2ServerDocCountLimit', 'GetKeyPairFromKeystore', 'GetLocale',
		'GetLocaleDisplayName', 'GetLocaleInfo', 'GetLocalHostIP', 'GetLuceeId',
		'GetMemoryUsage', 'GetMetadata', 'GetMetricData', 'GetNumericDate',
		'GetORMTransactionIsolation', 'GetPageContext', 'GetPrinterList',
		'GetProfileSections', 'GetProfileString', 'GetPropertyFile', 'GetPropertyString',
		'GetReadableImageFormats', 'GetSOAPRequest', 'GetSOAPRequestHeader',
		'GetSOAPResponse', 'GetSOAPResponseHeader', 'GetSystemFreeMemory',
		'GetSystemMetrics', 'GetSystemPropOrEnvVar', 'GetSystemTotalMemory', 'GetTagData',
		'GetTagList', 'GetTempDirectory', 'GetTempFile', 'GetTemplatePath', 'GetTickCount',
		'GetTimeZone', 'GetTimeZoneInfo', 'GetToken', 'GetTotalSpace',
		'getTransactionIsolation', 'GetUserRoles', 'GetVariable', 'GetVFSMetaData',
		'GetWriteableImageFormats', 'GuardDecode', 'GuardEncode', 'Hash', 'Hash40',
		'HKDFExpand', 'HKDFExtract', 'HMAC', 'HOTPGenerate', 'HOTPVerify', 'Hour',
		'HTMLCodeFormat', 'HTMLEditFormat', 'HtmlParse', 'IIf', 'ImageAddBorder',
		'ImageBlur', 'ImageCaptcha', 'ImageClearRect', 'imagecoderinfo', 'ImageCopy',
		'ImageCrop', 'ImageDrawArc', 'ImageDrawBeveledRect', 'ImageDrawCubicCurve',
		'ImageDrawImage', 'ImageDrawLine', 'ImageDrawLines', 'ImageDrawOval',
		'ImageDrawPoint', 'ImageDrawQuadraticCurve', 'ImageDrawRect', 'ImageDrawRoundRect',
		'ImageDrawText', 'ImageFilter', 'ImageFilterColorMap', 'ImageFilterCurves',
		'ImageFilterKernel', 'ImageFilterWarpGrid', 'ImageFlip', 'ImageFonts',
		'ImageFormats', 'ImageGetBlob', 'ImageGetBufferedImage', 'ImageGetEXIFMetadata',
		'ImageGetEXIFTag', 'ImageGetHeight', 'ImageGetIptcMetadata', 'ImageGetWidth',
		'ImageGrayscale', 'ImageInfo', 'ImageNegative', 'ImageNew', 'ImageOverlay',
		'ImagePaste', 'ImageRead', 'ImageReadBase64', 'ImageResize', 'ImageRotate',
		'ImageRotateDrawingAxis', 'ImageScaleToFit', 'ImageSetAntialiasing',
		'ImageSetBackgroundColor', 'ImageSetDrawingAlpha', 'ImageSetDrawingColor',
		'ImageSetDrawingStroke', 'ImageSetDrawingTransparency', 'ImageSharpen',
		'ImageShear', 'ImageShearDrawingAxis', 'ImageTranslate',
		'ImageTranslateDrawingAxis', 'ImageWrite', 'ImageWriteBase64',
		'ImageWriteToBrowser', 'ImageXORDrawingMode', 'IncrementValue', 'InputBaseN',
		'inquiryaisession', 'Insert', 'InspectTemplates', 'Int', 'internalRequest',
		'InterruptThread', 'Invoke', 'IsArray', 'IsBinary', 'IsBoolean', 'IsClosure',
		'IsCustomFunction', 'IsDate', 'isDebuggerEnabled', 'IsDebugMode', 'IsDefined',
		'IsEmpty', 'IsFileObject', 'isflushed', 'IsImage', 'IsImageFile', 'IsInstanceOf',
		'IsInThread', 'IsIPInRange', 'IsIPv6', 'IsJson', 'IsLeapYear', 'IsLocalHost', 'IsNull',
		'IsNumeric', 'IsNumericDate', 'IsObject', 'IsPDFObject', 'IsQuery', 'IsSimpleValue',
		'IsSOAPRequest', 'IsStruct', 'IsThreadInterrupted', 'IsUserInAnyRole', 'IsUserInRole',
		'IsUserLoggedIn', 'IsValid', 'IsWddx', 'IsWithinORMTransaction', 'IsWithinTransaction',
		'IsXML', 'IsXmlAttribute', 'IsXmlDoc', 'IsXmlElem', 'IsXmlNode', 'IsXmlRoot',
		'IsZipFile', 'JavaCast', 'JSONata', 'JsonToCbor', 'JSStringFormat', 'JwksLoad',
		'JwkToKey', 'JwtDecode', 'JwtSign', 'JwtVerify', 'KeystoreList', 'KeyToCose',
		'KeyToJwk', 'KeyToPem', 'KyberDecapsulate', 'KyberEncapsulate', 'LCase', 'Left', 'Len',
		'ListAppend', 'ListAvg', 'ListChangeDelims', 'ListCompact', 'ListContains',
		'ListContainsNoCase', 'ListDeleteAt', 'ListEach', 'ListEvery', 'ListFilter',
		'ListFind', 'ListFindNoCase', 'ListFirst', 'ListGetAt', 'ListGetDuplicates',
		'ListIndexExists', 'ListInsertAt', 'ListItemTrim', 'ListLast', 'ListLen', 'ListMap',
		'ListPrepend', 'ListQualifiedToArray', 'ListQualify', 'ListReduce',
		'ListRemoveDuplicates', 'ListRest', 'ListSetAt', 'ListSome', 'ListSort', 'ListToArray',
		'ListTrim', 'ListValueCount', 'ListValueCountNoCase', 'LJustify', 'LoadAISession',
		'Location', 'Log', 'Log10', 'LogAllThreads', 'LSCurrencyFormat', 'LSDateFormat',
		'LSDateTimeFormat', 'LSDayOfWeek', 'LSEuroCurrencyFormat', 'LSIsCurrency', 'LSIsDate',
		'LSIsNumeric', 'LSLCase', 'LSNumberFormat', 'LSParseCurrency', 'LSParseDateTime',
		'LSParseEuroCurrency', 'LSParseNumber', 'LSTimeFormat', 'LSUCase', 'LsWeek', 'LTrim',
		'ManifestRead', 'MarkdownToHtml', 'MavenExists', 'MavenExport', 'MavenImport',
		'MavenInfo', 'MavenLoad', 'Max', 'Metaphone', 'Mid', 'Millisecond', 'Min', 'Minute',
		'Month', 'MonthAsString', 'MonthShortAsString', 'NewLine', 'Now', 'NowServer',
		'NullValue', 'NumberFormat', 'ObjectEquals', 'ObjectLoad', 'ObjectSave',
		'ORMClearSession', 'ORMCloseAllSessions', 'ORMCloseSession', 'ORMEvictCollection',
		'ORMEvictEntity', 'ORMEvictQueries', 'ORMExecuteQuery', 'ORMFlush', 'ORMFlushAll',
		'ORMGetSession', 'ORMGetSessionFactory', 'ORMQueryExecute', 'ORMReload',
		'PagePoolClear', 'PagePoolList', 'ParagraphFormat', 'ParameterExists', 'ParseDateTime',
		'ParseNumber', 'PemToCertificate', 'PemToKey', 'Pi', 'PrecisionEvaluate',
		'PreserveSingleQuotes', 'Quarter', 'Query', 'QueryAddColumn', 'QueryAddRow',
		'QueryAppend', 'QueryClear', 'QueryClose', 'QueryColumnArray', 'QueryColumnCount',
		'QueryColumnData', 'QueryColumnExists', 'QueryColumnList', 'QueryConvertForGrid',
		'QueryCurrentRow', 'QueryDeleteColumn', 'QueryDeleteRow', 'QueryEach', 'QueryEvery',
		'QueryExecute', 'QueryFilter', 'QueryGetCell', 'QueryGetCellByIndex', 'QueryGetRow',
		'QueryInsertAt', 'QueryIsEmpty', 'QueryKeyExists', 'QueryLazy', 'QueryMap', 'QueryNew',
		'QueryPrepend', 'QueryRecordCount', 'QueryReduce', 'QueryRenameColumn', 'QueryReverse',
		'QueryRowByIndex', 'QueryRowData', 'QueryRowDataByIndex', 'QueryRowSwap',
		'QuerySetCell', 'QuerySetRow', 'QuerySlice', 'QuerySome', 'QuerySort', 'QueryToStruct',
		'QuotedValueList', 'Rand', 'Randomize', 'RandRange', 'RedisCommand',
		'RedisCommandLowPriority', 'RedisConnectionPoolInfo', 'REEscape', 'REFind',
		'REFindNoCase', 'ReleaseComObject', 'REMatch', 'REMatchNoCase', 'RemoveChars',
		'Render', 'RepeatString', 'Replace', 'ReplaceList', 'ReplaceListNoCase',
		'ReplaceNoCase', 'REReplace', 'REReplaceNoCase', 'RestDeleteApplication',
		'RestInitApplication', 'RestSetResponse', 'Reverse', 'Right', 'RJustify', 'Round',
		'RTrim', 'RunAsync', 's3addacl', 's3clearBucket', 's3copy', 's3createbucket',
		's3delete', 's3deletebucket', 's3download', 's3exists', 's3generatePresignedUrl',
		's3generateuri', 's3getacl', 's3getmetadata', 's3getversioninfo', 's3listBucket',
		's3listbuckets', 's3move', 's3read', 's3readBinary', 's3setacl', 's3setmetadata',
		's3upload', 's3write', 'Sanitize', 'SanitizeHtml', 'SCryptHash', 'SCryptVerify',
		'Second', 'SecretProviderGet', 'SecretProviderList', 'SecretProviderListNames',
		'SecretProviderRemove', 'SecretProviderSet', 'SendGatewayMessage', 'Serialize',
		'SerializeAISession', 'SerializeJSON', 'SessionCommit', 'SessionExists',
		'SessionInvalidate', 'SessionRotate', 'SessionStartTime', 'SetEncoding', 'SetLocale',
		'SetProfileString', 'SetPropertyString', 'SetTimeZone', 'SetVariable', 'Sgn', 'Sin',
		'SizeOf', 'Sleep', 'Soundex', 'SpanExcluding', 'SpanIncluding', 'SpreadSheetNew',
		'Sqr', 'SSLCertificateInstall', 'SSLCertificateList', 'StoreAddACL', 'StoreGetACL',
		'StoreGetMetadata', 'StoreSetACL', 'StoreSetMetadata', 'StringEach', 'StringEvery',
		'StringFilter', 'StringLen', 'StringMap', 'StringReduce', 'StringSome', 'StringSort',
		'StripCr', 'StructAppend', 'StructClear', 'StructCopy', 'StructCount', 'StructDelete',
		'StructEach', 'StructEvery', 'StructFilter', 'StructFind', 'StructFindKey',
		'StructFindValue', 'StructGet', 'StructInsert', 'StructIsEmpty', 'StructKeyArray',
		'StructKeyExists', 'StructKeyList', 'StructKeyTranslate', 'StructMap', 'StructNew',
		'StructReduce', 'StructSome', 'StructSort', 'StructToSorted', 'StructUpdate',
		'StructValueArray', 'SystemCacheClear', 'SystemOutput', 'Tan', 'ThreadData',
		'ThreadInterrupt', 'ThreadInterrupted', 'ThreadJoin', 'ThreadTerminate', 'Throw',
		'TimeFormat', 'ToBase64', 'ToBinary', 'ToNumeric', 'ToScript', 'ToString',
		'TOTPGenerateUri', 'TOTPSecret', 'TOTPVerify', 'Trace', 'TransactionCommit',
		'TransactionRollback', 'TransactionSetSavePoint', 'Trim', 'TrimWhitespace',
		'TrueFalseFormat', 'UCase', 'UcFirst', 'UnserializeJava', 'URLDecode', 'URLEncode',
		'URLEncodedFormat', 'URLSessionFormat', 'Val', 'ValidateJson', 'ValidateKeyPair',
		'ValueArray', 'ValueList', 'ValueRef', 'VerifyArgon2Hash', 'VerifyBCryptHash',
		'VerifySCryptHash', 'VerifySignature', 'WebserviceNew', 'WebSocketInfo', 'Week',
		'Wrap', 'WriteDump', 'WriteLog', 'WriteOutput', 'XmlChildPos', 'XmlElemNew',
		'XmlFormat', 'XmlGetNodeType', 'XmlNew', 'XmlParse', 'XmlSearch', 'XmlTransform',
		'XmlValidate', 'Year', 'YesNoFormat'
	].join('|');

	return {
		name: 'CFML',
		aliases: ['cfml', 'cfm', 'lucee'],
		case_insensitive: true,
		keywords: CFML_KEYWORDS,
		built_ins: CFML_BUILT_INS,
		contains: [
			hljs.COMMENT('<!--', '-->'),
			hljs.C_LINE_COMMENT_MODE,
			hljs.C_BLOCK_COMMENT_MODE,
			hljs.QUOTE_STRING_MODE,
			hljs.APOS_STRING_MODE,
			hljs.C_NUMBER_MODE,
			{
				className: 'meta',
				begin: /<\s*\/?\s*cfscript\b/i,
				end: /\/?\s*>/,
				relevance: 10
			},
			{
				className: 'tag',
				begin: /<\s*\/?\s*[A-Za-z_:][A-Za-z0-9_:.-]*/,
				end: /\/?\s*>/,
				contains: [
					{
						className: 'name',
						begin: /[A-Za-z_:][A-Za-z0-9_:.-]*/,
						relevance: 0
					},
					{
						className: 'attr',
						begin: /[A-Za-z_:][A-Za-z0-9_:.-]*/,
						end: /(?=\s|=|\/?>)/,
						relevance: 0
					},
					{
						begin: /=/,
						end: /(?=\s|\/?>)/,
						contains: [
							hljs.QUOTE_STRING_MODE,
							hljs.APOS_STRING_MODE,
							hljs.C_NUMBER_MODE
						]
					}
				]
			},
			{
				className: 'keyword',
				begin: '\\b(?:' + CFML_KEYWORDS + ')\\b'
			},
			{
				className: 'built_in',
				begin: '\\b(?:' + CFML_BUILT_INS + ')\\b'
			},
			{
				className: 'subst',
				begin: /#/, end: /#/,
				contains: [hljs.QUOTE_STRING_MODE, hljs.APOS_STRING_MODE, hljs.C_NUMBER_MODE]
			}
		]
	};
}
